### ISSUE TITLE
# noqa for individual imports in an import group are broken off into separate import statements

### ISSUE THREAD

**Issue by ljades** [PyCQA/isort#1004]
My project is noticing a strange behavior with `isort` and we're wondering if it's intentional design.

Right now, we are configured so that this is a valid import:
```
from very_long_import_name_close_to_limit import (
    a,
    b,
    c,
)
```

However, we want to add `# noqa` to the imports so that flake8 doesn't mark them as unused (for project-specific reasons, we want them to be directly importable from this file). However, doing so results in the following isort fix:

```
-from very_long_import_name_close_to_limit import (
-    a,  # noqa
-    b,  # noqa
-    c,  # noqa
-)
+from very_long_import_name_close_to_limit import a  # noqa
+from very_long_import_name_close_to_limit import b  # noqa
+from very_long_import_name_close_to_limit import c  # noqa
```

Is this intentional behavior? If so, why?

**Comment by timothycrosley** [comment]
It is semi-intentional. It is very hard to keep track of comment to import intention. It can become, essentially impossible on some wrap modes (many have more than one import per-line). isort is simply doing its best to avoid losing the comment information and the connection between that and the import - while supporting many wrap modes. That said, I'm going to keep this issue open, as any improvements to this are always welcome.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
The conversation here: https://github.com/PyCQA/isort/issues/1415 has confirmed for me that isort is doing the right thing in this case. The above example is ambiguous across linters, and in fact will not be understood by the commonly used flake8, whereas isorts correctly maps to flake8s expectation, and ensures comment to import association is preserved long term.

Thanks!

~Timothy
