### ISSUE TITLE
All venv packages are being treated as third party

### ISSUE THREAD

**Issue by salimuddin87** [PyCQA/isort#1439]
Can I provide in setup.cfg such that other than first party, everything is third party?
```
known_third_party = everything in venv other that app dir
known_first_party = app
```

we have a lot of third party tools. It's not feasible for us to mention all third party in setup file.

isort version: 3.4.3
python: 3.6

**Comment by timothycrosley** [comment]
Hi @salimuddin87,

Thank you for being a long time user of isort!

> isort version: 3.4.3

There have been 2 major releases (and several minor releases) since 3.4.3 was released February of 2014. Since you are using Python 3.6, the newest version of isort should be compatible with your project, and includes many benefits including improved module placement, that defaults all packages to third party other than those listed as first_party, or included in src_paths. See here: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/ or if you need help upgrading just let me know!

If, for any reason, you need to stay on 3.4.3, you can specify that the default is `THIRD_PARTY` instead of `FIRST_PARTY` by modiying this setting: https://pycqa.github.io/isort/docs/configuration/options/#default-section

But, I do really encourage some time be spent upgrading as there are many improvements in the latest version, beyond just that change! See: https://pycqa.github.io/isort/docs/major_releases/introducing_isort_5/ & https://timothycrosley.com/project-8-isort5.

Thanks!

~Timothy
