### ISSUE TITLE
Upgrade link to isort5 upgrade guide used in warnings

### ISSUE THREAD

**Issue by karrtikr** [PyCQA/isort#1448]
Links are no longer hosted on `https://timothycrosley.github.io/` so many upgrade links are now invalid. For eg. https://pycqa.github.io/isort/docs/warning_and_error_codes/W0500/

**Comment by timothycrosley** [comment]
Thanks for the heads up! The links are fixed in development, and most should now have redirects in place. if you see any more that are not correctly redirected, I'll hurry to put more redirects in place here: https://github.com/timothycrosley/timothycrosley.github.io/tree/gh-pages/isort.

Thanks!

~Timothy
