### ISSUE TITLE
Passing file paths to CLI via pipe?

### ISSUE THREAD

**Issue by esmail** [PyCQA/isort#1508]
I'm trying to do something like the following:
```bash
echo <some file paths> | isort ...
```

Is this possible?

(Technically, my use case is a touch more complex, as I'm trying to pass a `git-diff --name-only ...` list of changed files from my host, which doesn't have `isort`, to my Docker container, which doesn't have `git`)

**Comment by timothycrosley** [comment]
Hi! 

Thanks for reaching out.

At first glance, this feels to me more like a question that is better answered as a bash (or other terminal) question rather than an isort question. If you just want to pass a bunch of files to isort (or any other terminal application) you could use something like the answer in this question: https://serverfault.com/questions/641983/how-to-pass-command-output-as-several-arguments-to-another-command

If you want to ensure you have no performance penalty from multiple startups, which really should be insignificant especially if this is the output of a diff, you could write a simple service such as:

```
import hug
import isort

CONFIG = isort.Config(config_location)


@hug.get()
def isort_file(filename: str):
    file = isort.file(filename, config=CONFIG)
```

And then pass the filename for each invocation. But again, if you are just passing in files from a diff, simply passing those file names as the arguments to isort should be sufficient. Realistically, you probably don't even need to split it across multiple invocations. You'll know you've reached that point if you run into this error: https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command.

I hope this helpful! Let me know if this resolved your issue or if there is further follow up questions.

Thanks!

~Timothy

**Comment by esmail** [comment]
Thanks, I was able to work around it with command substitution from the shell like the following:
```bash
docker-compose run --rm my_image isort $$(git diff --name-only --diff-filter=ACMR origin/my_branch -- '**.py')
```

So then I take it that the `isort` CLI does not allow specifying files from stdin?

**Comment by timothycrosley** [comment]
> So then I take it that the isort CLI does not allow specifying files from stdin?

That's correct. isort supports sorting file content from stdin, but not filenames. As far as I'm aware this is inline with most CLI tools, including Black as there are other ways (like the one you used) to pass a filenames in from the output of another command. It would be easy to add support if there was a compelling and common enough case for it.

I'm glad you were able to get your immediate issue resolved!

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Going to close this ticket for now, @esmail or anyone else, please feel empowered to open a new issue or comment here if this is a feature you want or need within isort.

Thanks!

~Timothy
