### ISSUE TITLE
Unexpected output when using VERTICAL_HANGING_INDENT mode

### ISSUE THREAD

**Issue by youtux** [PyCQA/isort#1514]
Given this input module:
```python
# asd.py

from django.utils.translation import ugettext, ugettext_lazy as _
```
Running `isort --multi-line VERTICAL_HANGING_INDENT asd.py`, the imports are reordered this way:
```python
# asd.py

from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _
```
While I would have expected the imports to be left intact.

Is there a reason why the output is like this or is it a bug?

PS: Thanks for this amazing project!

**Comment by timothycrosley** [comment]
Hi @youtux,

Thanks for reaching out! The reason is just that alias imports are the exception, and so isort by default calls them out on their own line to help draw attention to the alias. However, not everyone likes this style! You can set the [combine_as_imports](https://pycqa.github.io/isort/docs/configuration/options/#combine-as-imports) if you prefer to have them on the same line as other imports.

Hope this helps!

~Timothy

**Comment by youtux** [comment]
Thanks for your quick answer! I still don't understand why the whole `from django.utils.translation import ` part is replicated though.
Wouldn't it make more sense then to combine to multilines by default instead? Like this:
```python3
# asd.py

from django.utils.translation import (
    ugettext,
    ugettext_lazy as _,
)
```

**Comment by timothycrosley** [comment]
It's just because calling it out on it's own line, while repeating the initial part is an approach that works well across all wrapping modes. Additionally, it allows these imports, which isort sees as exceptions, to more cleanly have formatting comments on just them. Tools like flake8 are based on statement lines, so if the import is included in the same statement, there is no way to add a # noqa to just that import.

**Comment by youtux** [comment]
I understand, thanks.
