### ISSUE TITLE
Bug with sorting imports

### ISSUE THREAD

**Issue by spinelsun** [PyCQA/isort#1563]
Hi,

I am using Microsoft's python extension which uses the library to sort imports.
In the last few versions, something started to go wrong, and the sorting doesn't work.
I opened a [bug issue](https://github.com/microsoft/vscode-python/issues/14399) in the repository but they said it is something in this library.
The details of what is actually happening and the right behavior are in the link above :arrow_up:

 Thanks

**Comment by timothycrosley** [comment]
Hi @spinelsun,

I'm sorry you are experiencing this issue! Have you tried running isort directly in your project and seeing if the issue is indeed with isort? Does your project have an isort config? I've downloaded the latest version of the plugin, and I use vscode myself, and it is still working for me. Additionally, your expected output doesn't match the output isort gives by default, but isort is very configurable.

If possible can you past the output of:
`isort FILENAME --show-settings` 
?

Thanks!

~Timothy

**Comment by spinelsun** [comment]
Hi,

So I tried to run isort directly and it worked fine.
I reopened the issue in the extension repo again and informed them that the problem is not in the library.

Thanks for the quick reply
