### ISSUE TITLE
The format on warnings is confusing

### ISSUE THREAD

**Issue by Mithil467** [PyCQA/isort#1568]
Currently when I run : `isort -m 3 -tc project_name/ --check`
I get the following output - 
```
Skipped 4 files
/home/mithil/.local/lib/python3.8/site-packages/isort/main.py:995: UserWarning: W0502: The following deprecated single dash CLI flags were used and translated: -tc!
  warn(
/home/mithil/.local/lib/python3.8/site-packages/isort/main.py:1004: UserWarning: W0500: Please see the 5.0.0 Upgrade guide: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/
  warn(
```
I noticed the weird `warn(` being printed. I think it might be printing the source code on line 995 and 1004, which is just `warn(` as the actual string parameters are formatted and placed on the next lines as - 
```
warn( # This line
"String1"
)
```

This behaviour can be modified to not print the source code.

Further, we may also probably just remove the file-name and line-number.

[Similar SO solution](https://stackoverflow.com/a/2187390)

If you feel this is a valid issue, I'd be happy to make a PR :)

**Comment by timothycrosley** [comment]
isort uses warnings to stick with Python standards, and to allow the warnings to be suppressed by users in the standard Python way. I think if warn is formatted this way, throughout Python, by default, isort should do the same. From what I can see the way to modify the format, changes it globally, which is no good for isort as it can be used both as a library and a CLI application. And, ofcourse, even if the modification was done only at CLI level, some use the CLI code path as an API for various reasons. If I'm wrong and there's a clean way to only change the output for isort, I'm happy to accept a PR that does so, otherwise if you think the warning format is unpleasant, it sounds like that's a more broad issue that should be directed to CPython.

Thanks!

~Timothy

**Comment by Mithil467** [comment]
I agree with all your points.
Including isort in any other project will also affect the way warnings are printed there.

What if we backup the original formatting function, and then change it, use it, and then at the end, just replace it back to the original formatting?
Like so -
```
def custom_formatwarning(msg, *args, **kwargs):
    return str(msg) + '\n'

original_function = warnings.formatwarning
warnings.formatwarning = custom_formatwarning
warn("Some warning")
warn("Another warning")
warnings.formatwarning = original_function
```

**Comment by timothycrosley** [comment]
I agree with the central premise of this ticket that the formatting of warnings is less then ideal. I think your goals here are all in the right direction. However, after thinking about it, I simply don't think this is something isort should change. Changing a global setting, even if you store the original, can lead to very confusing behavior for downstream project users, and makes it hard not to introduce thread / async unsafe code accidentally. If an issue is made to improve the format of Warnings at the CPython level, or to make them easier to change at a project by project level safely, I'll be one of the first to +1 it. I just don't think at this time, this is an isort issue.

Thanks!

~Timothy

**Comment by Mithil467** [comment]
Changng a global setting didn't sound right to me too, as it may involve unnecesary complications down the line, but I was just not sure. I agree with you.
I really appreciate your time to explain it all :)

Thanks!

**Comment by Akuli** [comment]
Another option would be to use `logging` instead of `warnings`. It's also standard-library, and much more configurable.
