### ISSUE TITLE
Leading space is removed from wrong line

### ISSUE THREAD

**Issue by bersbersbers** [PyCQA/isort#1575]
Using v5.6.4:

```
:/tmp> echo -e "import os\n import os" | isort -
```

Actual:
```
mport os
 import os
```

Expected:
```
import os
import os
```
or *maybe*
```
import os
 import os
```

**Comment by timothycrosley** [comment]
isort isn't intended to be ran on invalid code, `--atomic` can be used (at a performance penalty) to ensure the code is valid before being sent to isort to avoid errors like this. Is there a valid code snippet that also triggers this?

**Comment by bersbersbers** [comment]
> isort isn't intended to be ran on invalid code, `--atomic` can be used (at a performance penalty) to ensure the code is valid before being sent to isort to avoid errors like this.

I see, and I agree. However, this is the default experience that VS Code users with Python extension are getting. `isort` is called regardless of whether the code is valid or not.

> Is there a valid code snippet that also triggers this?

Not that I am aware of.

**Comment by timothycrosley** [comment]
I'm sorry you are experiencing this! I think, if it's okay with you, I might morph this ticket into a more general safety check around isort calls by default. While, I want to avoid a full syntax check like `--atomic` does (so that isort will maintain compatibility with new versions of Python, even when they are using new syntaxt by default). Maybe there are some light weight checks we can do to avoid the worst outcomes when invalid code is passed in.

**Comment by bersbersbers** [comment]
> if it's okay with you, I might morph this ticket into a more general safety check around isort calls by default. 

Totally - I know how to deal with this, and version control helps in the worst case. This was just a service issue to make `isort` people aware of it.
