### ISSUE TITLE
Problem with noqa comment

### ISSUE THREAD

**Issue by wesleybl** [PyCQA/isort#1581]
I have import:

```python
from collective.js.bootstrap.testing import COLLECTIVE_JS_BOOTSTRAP_FUNCTIONAL_TESTING  # noqa
```

isort suggests:

```diff
-from collective.js.bootstrap.testing import COLLECTIVE_JS_BOOTSTRAP_FUNCTIONAL_TESTING  # noqa
+from collective.js.bootstrap.testing import (
+    COLLECTIVE_JS_BOOTSTRAP_FUNCTIONAL_TESTING  # noqa,
+)
```

If I use the suggestion and run isort again, it suggests:

```diff
 from collective.js.bootstrap.testing import (
-     COLLECTIVE_JS_BOOTSTRAP_FUNCTIONAL_TESTING  # noqa,
+    COLLECTIVE_JS_BOOTSTRAP_FUNCTIONAL_TESTING  # noqa,,
 )
```

That is, he suggests adding a comma at the end of the comment to each run.

I'm using `Python` 2.7.17 with `isort` 4.3.21.

My settings:

```ini
[isort]
force_alphabetical_sort = True
force_single_line = False
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
use_parentheses = True
lines_after_imports = 2
line_length = 88
not_skip =
    __init__.py
skip =
```

**Comment by timothycrosley** [comment]
Hi @wesleybl, 

I'm sorry you are encountering this error! Unfortunately, this project does not have the capacity to support older major releases, meaning: the version of isort you are using is no longer supported by the project, and version of Python you are running is no longer supported by the Python community at large. The good news is that this is fixed in the latest version of isort.

I know that upgrading a larger project to Python3+ can be a challenge, however, you can run isort outside of your project's Python version and still target Python2 python. Please see the upgrade guide here and let me know if you have any questions: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/

Thanks!

~Timothy
