### ISSUE TITLE
isort thinks third party library is first party if repo directory name is same as third party library name

### ISSUE THREAD

**Issue by ironfoot** [PyCQA/isort#1595]
## summary

If the repo directory name is same as a third party library name, isort gets confused.
Note that it's not the package name or module name but the local repo root directory name.

## issue

Both are third party libraries so this is correct order.

```python
import requests
import urllib3
```

But isort disagrees.
```bash
❯ isort --diff .
--- /Users/ironfoot/requests/mypackage/mymodule.py:before       2020-11-11 01:32:50.401128
+++ /Users/ironfoot/requests/mypackage/mymodule.py:after        2020-11-11 01:32:57.770363
@@ -1,2 +1,3 @@
+import urllib3
+
 import requests
-import urllib3
Skipped 2 files
```

In essece, isort wants
```python
import urllib3

import requests
```

## How to reproduce

repo structure,
```bash
requests/
    mypackage/
        __init__.py
        mymodule.py
```

mymodule.py
```python
import requests
import urllib3
```

virtualenv
```bash
❯ pip freeze
certifi==2020.11.8
chardet==3.0.4
idna==2.10
isort==5.6.4
requests==2.24.0
urllib3==1.25.11
```

**Comment by timothycrosley** [comment]
I don't think isort is wrong here, it simply hasn't been presented with enough information to know definitively what you want. Some repos do have their package name as the repo name, and rely on no further nesting. Further, no `__init__.py` is required for namespace packages. isort provides solutions to make this explicit and achieve the desired behaviour:

You can manually specify mypackage as the src path for isort:
```
[tool.isort]
src_paths=mypackage
```

Or, specify requests as a known_third_party:
```
[tool.isort]
known_third_party=requests
```

**Comment by ironfoot** [comment]
Thanks for the quick response.

If I understand correctly the case you explain is,
Package name is repo name not through the developer explicitly configuring the package name that happens to be same as the repo name but rely on which directory the repo was cloned into. If you run 'git clone remote-url other-name' than the package name changed and code is broken. I'd imagine that'll be the corner case not the common case. (I don't have any data to back this up)

So, in a situation where a name is both a third party library name but also a repo root directory name, isort needs to choose between third party library and first party library.
It seems like choosing first party library is optimizing for the corner case.

**Comment by timothycrosley** [comment]
I think it might be helpful to know a bit of background in this case:

- isort really doesn't know or attempt to have any idea of what's "thirdparty" it tried to do so in the past but that led to a world of hurt because there are so many and ever-expanding ways to define third party requirements, and they don't even always live in consistent spots parallel to local source code. So instead everything it can't identify in anyway as local is third party. This importantly means it doesn't really matter what is in your requirements.txt file or virtual environment or equivalent to isort. it never looks at it.
- isort primarily is looking at the disk paths, relative to where you put the config file. The fact that the path is a git repo matters less then if it has a .isort.cfg in it - though it will stop looking for configs at common source roots (.git, .hg, etc)

I think the common case if you have a directory path like this, with those considerations in mind, is that requests represents a local project. isort makes it easy to make it explicit what the scope of your local project is however, using a config at the root of your repo that specifies your exact src paths.

**Comment by ironfoot** [comment]
Thanks again. I understand better now.

My intuition is that src_paths should, by default, include directories in the root path excluding the root itself.
But maybe it is the case that many people use a pattern that feels unnatural to me.
I'll fix my issue with the src_paths config.

**Comment by seanswyi** [comment]
@timothycrosley A few years late but had a question regarding this same issue. I was specifying `known_third_party` for a module in my `.isort.cfg` file but isort was still failing to recognize it. After doing some searching I found a [Stack Overflow answer](https://stackoverflow.com/questions/63864777/is-there-a-way-for-isort-to-automatically-detect-firstparty-vs-thirdparty-module) that said to run `isort --resolve-all-configs .`. Running that actually solved the issue but I'm not 100% clear if that was what did it. Is it necessary to run that command after changing your config?
