### ISSUE TITLE
First party depends on config file location, when using --settings argument.

### ISSUE THREAD

**Issue by ironfoot** [PyCQA/isort#1597]
## Issue
When I run isort command by explicitly telling where isort config file is,
The outcome shouldn't change depending on where the config file is located.
It defeats the purpose of allowing to put the config file somewhere else and explicitly letting isort know where it is.

## Repro

Directory structure.
```
repro/
    mypakcage/
        mymodule.py
    tests/
        test_mymodule.py
    .isort.cfg
    settings/
        .isort.cfg
```

Two config files have identical content.
```
[settings]
profile=black
src_paths=mypackage
```

test_mymodule.py
```python
import requests

import mypackage
```

I'm running below command from root of the repo.
If I use the config file at root, it's all correct.
```bash
❯ isort -v --settings .isort.cfg --diff . -v

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.6.4

else-type place_module for requests returned THIRDPARTY
else-type place_module for mypackage returned FIRSTPARTY
```

If I use config file in a different path, `mypackage` is not recognized as first party.
```bash
❯ isort -v --settings settings/.isort.cfg --diff . -v

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.6.4

else-type place_module for requests returned THIRDPARTY
else-type place_module for mypackage returned THIRDPARTY
--- /Users/ironfoot/workspace/repro/tests/test_mymodule.py:before	2020-11-12 11:48:54.652133
+++ /Users/ironfoot/workspace/repro/tests/test_mymodule.py:after	2020-11-12 12:17:50.343466
@@ -1,3 +1,2 @@
+import mypackage
 import requests
-
-import mypackage
```

Having or not having `src_paths` in the config file doesn't change the outcome.

**Comment by timothycrosley** [comment]
Hi ironfoot :wave:,

I can see how this behaviour could be counter-intuitive in some cases, and I'm sorry it caused confusion! The problem with the src-paths, is and other config settings, is that realistically there is no option other than to make them relative to the config file location. You can still accomplish what you want simply by either

A) Making the src_path setting, point to the correct src path relative to where the config lives:

```
  [settings]
  profile=black
  src_paths=../mypackage
```

Or, B) using known_first_party instead of src_paths:

```
  [settings]
  profile=black
  src_paths=
  known_firstparty=mypackage
```

Now, to answer the question of why this is an unavoidable reality, if isort didn't behave this way, how would it know where mypackage (as a directory) was located? It could do it based on the CWD but that would be even less predictable, and things, and then you could no longer simply run isort on files from the CLI and rely on it picking up your config. I hope you find this info and one of these two options helpful.

Thanks!

~Timothy

**Comment by ironfoot** [comment]
What you explain makes sense but maybe I was expecting more, some sort of root detection based on CWD.
Some other tools like mypy, pylint, pytest doesn't rely on CWD or location of config file.
That is, as long as I pass in the config file path as argument.

I was caught by surprise when pylint, which entirely relies on isort for import ordering, was disagreeing with isort once I moved config files to a non-default location.
A larger context is that I was trying to create a package with various tools and config files so it can be installed and used uniformly across different repos.

Seems like for isort I'll have to copy over the config to root of repo.
Anyway thanks for the response.
