### ISSUE TITLE
5.7.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [PyCQA/isort#1630]
```
+ cd isort-5.7.0
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing isort.egg-info/PKG-INFO
writing dependency_links to isort.egg-info/dependency_links.txt
writing entry points to isort.egg-info/entry_points.txt
writing requirements to isort.egg-info/requires.txt
writing top-level names to isort.egg-info/top_level.txt
reading manifest file 'isort.egg-info/SOURCES.txt'
writing manifest file 'isort.egg-info/SOURCES.txt'
running build_ext
Broken 1 paths
```

**Comment by timothycrosley** [comment]
@kloczek Do you need to run tests in this manor? The project officially uses `./scripts/test.sh` to run the test suite, and as noted in your given output:

`WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.`

**Comment by Abdur-rahmaanJ** [comment]
@timothycrosley Just a comment, adding tests via .sh excludes windows contributors, which is quite uncomfortable since py was supposed to be cross-platform

**Comment by kloczek** [comment]
> Do you need to run tests in this manor? The project officially uses ./scripts/test.sh to run the test suite, and as noted in your given output:

Why this project cannot huook under standard way of test suite execution provided by setuptool framework?

**Comment by timothycrosley** [comment]
@Abdur-rahmaanJ, certainly my intention isn't to avoid any contributors from any OS! It is a bit of a muddled area now however, as the Linux Subsystem for Windows and Docker are fairly excepted and supported development paths these days on Windows. In any case, direct usage of pytest is also supported (`pytest tests/unit`)

> Why this project cannot huook under standard way of test suite execution provided by setuptool framework?

I'll be 100% honest, I'm not even sure how you ran that command as this project doesn't contain a setup.py file since it uses poetry, my best guess it that you ran it against the source distribution. I'm happy to support it, but not sure the best way to. The message about it being deprecated is from setuptools I believe so may not be worth the effort.
