### ISSUE TITLE
How to skip __init__.py files

### ISSUE THREAD

**Issue by jeffwillette** [PyCQA/isort#1632]
Hi. Sometimes the import ordering in __init__.py is sensitive so I would like to ignore sorting the __init__.py files. I am using this as a vim plugin so I would like to just pass the option as a CLI arg from my vim setup. I couldn't get it to work so I tried it on the plain CLI and I cannot figure out how the `--skip` arg works...

```
>>>isort module/__init__.py --diff --skip __init__
--- /st2/jeff/PAD/regression/__init__.py:before 2021-01-04 16:22:00.244654
+++ /st2/jeff/PAD/regression/__init__.py:after  2021-01-04 16:30:54.542909
@@ -3,5 +3,5 @@
 from .mc_dropout import *
 from .r1bnn import *
 from .swag import *
+from .trainer_base import *
 from .workers import *
-from .trainer_base import *
```

As you can see, it still seems as though it is sorting the file in question even though I told it to skip init files. I have already tried all of the different versions of using `__init__.py` or just `init` as the arg. I also tried using the option `--skip-glob` but I had no luck.

How can I get this to work and to skip the `__init__.py` files?

**Comment by timothycrosley** [comment]
Hi @jeffwillette,

Good questions! Hopefully, I can help lead you to a workable solution. Looking at your example, I notice two things:

1. Skip takes file names so instead of `--skip __init__` use `--skip __init__.py` 
2. isort, like flake8 and other formatters and  linters, doesn't filter files explicitly passed in by default, only ones that are included via a directory. isort does provide the `--filter-files` flag to filter even explicitly passed in files.

Taken together, I believe the following will accomplish what you are after:

```isort module/__init__.py --diff --skip __init__ --filter-files```

**Comment by jeffwillette** [comment]
Yes that seems to work. Thank you for the detailed reply
