### ISSUE TITLE
isort breaks out lines when you alias in "from x import y"

### ISSUE THREAD

**Issue by dannysepler** [PyCQA/isort#1671]
Not sure if this is a bug? But if you run isort on:

```python
from typing import Dict, List as TypedList, Set
```

it turns into

```python
from typing import Dict
from typing import List as TypedList
from typing import Set
```

But I would think It shouldn't do anything? Or just put List at the end?

**Comment by timothycrosley** [comment]
This is intentional, as aliases are slightly outside direct and normal usage, and so the project sees them as worth making more prominent by placing them on separate lines so they can't be missed. This is one of many areas where there is no clear guidance in PEP8 and many valid decisions that all come down to formatting preference and priority.

You can modify this behavior and combine them if you prefer the combined formatting style using the [combine_as_imports](https://pycqa.github.io/isort/docs/configuration/options/#combine-as-imports) setting.

Hope this is helpful!

~Timothy
