### ISSUE TITLE
local file is not sorted correctly

### ISSUE THREAD

**Issue by Siecje** [PyCQA/isort#1674]
I have a project with this structure

```
mypackage/
tests/
tests/atils.py
tests/test_mypackage.py
# no __init__.py in tests
```

inside `tests/test_mypackage.py` atils is imported before mypackage

```
import atils

from mypackage.foo import bar
```

Here is my isort config

```
[tool.isort]
profile = "black"
known_third_party = ["baz"]
force_sort_within_sections = true
order_by_type = false
lines_after_imports = 2
skip_glob = "modules"

```

**Comment by timothycrosley** [comment]
Where is the config file located? How is isort ran?

**Comment by Siecje** [comment]
The config is in pyproject.toml

```
pyproject.toml
mypackage/
tests/
venv/
```

In this directory I am running

```shell
venv/bin/python -m isort .
```

**Comment by timothycrosley** [comment]
Would you be able to try turning `auto_identify_namespace_packages=False` (https://pycqa.github.io/isort/docs/configuration/options/#auto-identify-namespace-packages) and see if this resolves the issue?

**Comment by Siecje** [comment]
That setting didn't change the isort output.

**Comment by Siecje** [comment]
The file that is not sorted correctly is in `tests/` which doesn't have a `__init__.py` so I don't believe it is a namespace package.

**Comment by timothycrosley** [comment]
Ah, sorry I haven't circled back on this in a while!

Right now to get this to work in isort you would simply need to have the tests directory added as a source path:

https://pycqa.github.io/isort/docs/configuration/options/#src-paths

`isort . --src . --src tests`

**Comment by Siecje** [comment]
That removes the line between the atils import and mypackage but doesn't move it to the LOCALFOLDER section.

Before
```Python
import atils

from mypackage import foo
```

After 

```Python
import atils
from mypackage import foo
```

If instead of `atils.py` it was `utils.py` it is sorted after but there is no new line after the mypackage import.

**Comment by timothycrosley** [comment]
Ah! That's interesting! Local folder right now, in practice, really just operates as "Dot prefixed import". But I can easily see how that would be confusing, or not desired in this case. You can get the styling you want still, if your exact case is as simple as this example, but this does lead me to believe there is some room here for more smarts within isort grouping:

```cfg
sections=FUTURE,STDLIB,THIRDPARTY,MYPACKAGE,FIRSTPARTY,LOCALFOLDER
known_mypackage=mypackage
src_paths=.,tests
```

More info here: https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering/

I think long term there is some room to improve how this is done, I wonder what really makes the most since? Merge these kind of imports with dot imports? Place them in there own section?

**Comment by Siecje** [comment]
Thanks! That sorts the imports how I want.

**Comment by timothycrosley** [comment]
Closing for now, since the immediate question was answered, but tagging as an idea to look into for a future release
