### ISSUE TITLE
Extra line added after last import when enclosed in comments when treat_all_comments_as_code enabled

### ISSUE THREAD

**Issue by bobwalker99** [PyCQA/isort#1681]
Easier to demonstrate than describe:  
```
import b
import c

# pylint: disable=wrong-import-order
import a
# pylint: enable=wrong-import-order
```
becomes:
```
import b
import c

# pylint: disable=wrong-import-order
import a

# pylint: enable=wrong-import-order
```

I've added a test assertion to `tests/unit/test_ticketed_features.py` but I'm new to this code and struggling to see how to fix this. Happy to attempt a fix/pull request if someone can nudge me in the right direction?

To reproduce, add this to `test_treating_comments_as_code_issue_1357`:
```
assert (
        isort.code(
            """import b

import c
# pylint: disable=wrong-import-order
import a
# pylint: enable=wrong-import-order
""",
            treat_all_comments_as_code=True,
        )
        == """import b
import c

# pylint: disable=wrong-import-order
import a
# pylint: enable=wrong-import-order
"""
    )

**Comment by timothycrosley** [comment]
This is a tough one. Normally, independent to what comments they are, generally people want lines between the import blocks and the comment blocks. You can disable these lines, but while that may make this particular block of code better looking for your style preference, it would break also change it in ways you likely won't like. 

For instance:

```
import os
# my comment for constant
CONSTANT = 1
```

Instead of:
/
```
import os

# my comment for constant
CONSTANT = 1
```

isort could try to parse these comments, but that's a lot to maintain, as it's dependent on the decisions of a different project.
I think the best solution is just to tell isort to skip that one import completely:

```
# pylint: disable=wrong-import-order
import a  # isort: skip
# pylint: enable=wrong-import-order
```

Let me know if this works for you!

~Timothy

**Comment by timothycrosley** [comment]
Going to close for now, if this is still an issue for you, let me know and I'll reopen!

Thanks!

~Timothy

**Comment by bobwalker99** [comment]
Sorry for the slow response - yes, that sounds reasonable, and the workaround works, thanks for looking :-)
