### ISSUE TITLE
Support for magic trailing comma

### ISSUE THREAD

**Issue by jack1142** [PyCQA/isort#1683]
Black auto-explodes imports, collections, function calls, etc. when they contain a trailing comma:
https://github.com/psf/black/blob/master/docs/the_black_code_style.md#the-magic-trailing-comma

This means that even though this would fit into one line:
```py
from seven_dwwarfs import (
    Grumpy,
    Happy,
    Sleepy,
    Bashful,
    Sneezy,
    Dopey,
    Doc,
)
```
Black will NOT convert it into this:
```
from seven_dwwarfs import Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey, Doc
```
As long as the import list contains a trailing comma.

`isort` currently does not have the magic trailing comma handling as far as I can tell and will collapse the import list if it can fit within the line length limit.

**Comment by timothycrosley** [comment]
I agree, this would be great to add! The only saving grace about the current behavior is that since it forces a trailing comma, it is always black compatible - but it would be nice to be compatible with the spirit of black's formatting approach as well.

**Comment by dzieciou** [comment]
Exactly, it also makes `pylama` checks with isort problematiic after applying black :-(

Here's my use case to reproduce the problem:
```
pip install isort==5.8.0 black==20.8b1
```

I have the following file `test.py`

from collections import (defaultdict, namedtuple,)

that black turns into multi-line import because of the trailing comma:

from collections import (
    defaultdict,
    namedtuple,
)

However, `isort --profile black` does not consider to respect that and changes that into single-line import

from collections import defaultdict, namedtuple

**Comment by onerandomusername** [comment]
Hi, I'm having this problem myself, I would really appreciate support for the magic trailing comma, but I understand it would be another configuration option. If I had some ideas to what to name it, I could try to implement this myself, but I haven't looked at the isort source yet, so that may not be possible for me to do,

**Comment by jack1142** [comment]
>  If I had some ideas to what to name it, I could try to implement this myself,

`magic_trailing_comma` or `split_on_trailing_comma` probably make most sense. The former probably makes it clear for Black users while the latter better explains what the option does and seems to be more inline with other option names in isort.

Either way, I think that the name should be the least of your concerns when it comes to implementing it 😄 
It would be a matter of a simple find&replace if someone comes with a better name during PR review stage.

**Comment by onerandomusername** [comment]
Okay, I'm going to try to work on this \:)
