### ISSUE TITLE
THIRDPARTY module detected as FIRSTPARTY in 5.0

### ISSUE THREAD

**Issue by netsandbox** [PyCQA/isort#1696]
isort installation method:

```shell
python3 -m venv --clear venv
. venv/bin/activate
pip install "isort~=4.0"
pip install "isort~=5.0"
```
I have no isort config file, so just using the defaults.

My scripts/hostgroups.py imports:

```python
import argparse
import sys

from ansible.inventory.manager import InventoryManager
from ansible.parsing.dataloader import DataLoader
```

With isort 4.3.21 everything is fine:
```shell
isort --diff --verbose scripts/hostgroups.py 

/#######################################################################\

     `sMMy`
     .yyyy-                                                      `
    ##soos##                                                    ./o.
          `     ``..-..`         ``...`.``         `   ```` ``-ssso```
     .s:-y-   .+osssssso/.     ./ossss+:so+:`    :+o-`/osso:+sssssssso/
     .s::y-   osss+.``.``     -ssss+-.`-ossso`   ssssso/::..::+ssss:::.
     .s::y-   /ssss+//:-.`   `ssss+     `ssss+   sssso`       :ssss`
     .s::y-   `-/+oossssso/  `ssss/      sssso   ssss/        :ssss`
     .y-/y-       ````:ssss`  ossso.    :ssss:   ssss/        :ssss.
     `/so:`    `-//::/osss+   `+ssss+-/ossso:    /sso-        `osssso/.
       \/      `-/oooo++/-      .:/++:/++/-`      ..           `://++/.


         isort your Python imports for you so you don't have to

                            VERSION 4.3.21

\########################################################################/

from-type place_module for __future__ returned FUTURE
else-type place_module for argparse returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for ansible.inventory.manager returned THIRDPARTY
from-type place_module for ansible.parsing.dataloader returned THIRDPARTY
```

isort 5.8.0 detects `ansible.inventory.manager` as a FIRSTPARTY module and `ansible.parsing.dataloader`as a THIRDPARTY module.
```shell
isort --diff --verbose scripts/hostgroups.py 

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.8.0

from-type place_module for __future__ returned FUTURE
else-type place_module for argparse returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for ansible.inventory.manager returned FIRSTPARTY
from-type place_module for ansible.parsing.dataloader returned THIRDPARTY
--- /<redacted>/scripts/hostgroups.py:before	2021-03-24 09:41:08.581392
+++ /<redacted>/scripts/hostgroups.py:after	2021-03-24 12:50:24.637479
@@ -5,8 +5,9 @@
 import argparse
 import sys
 
+from ansible.parsing.dataloader import DataLoader
+
 from ansible.inventory.manager import InventoryManager
-from ansible.parsing.dataloader import DataLoader
 
```

I have read the [5.0.0 Upgrade Guide](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/) and couldn't find a reason why the above behavior should be correct. Maybe I have missed something?

If i run isort 5.8.0 with `--old-finders` `ansible.inventory.manager` is detected as THIRDPARTY and everything is also fine:
```shell
isort --diff --old-finders --verbose scripts/hostgroups.py 

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.8.0

from-type place_module for __future__ returned FUTURE
else-type place_module for argparse returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for ansible.inventory.manager returned THIRDPARTY
from-type place_module for ansible.parsing.dataloader returned THIRDPARTY

```

**Comment by timothycrosley** [comment]
@netsandbox I'm sorry you are experiencing this!

Do you by any chance have a an ansible directory next to the source file in question?

In any case, can you check the output of running the following from a the Python environment isort is installed in;

```python
isort.place.module_with_reason("from ansible.inventory.manager")
```

This may be able to let you know why, it's hard to fully tell remotely, since the new finder is based of your source structure, and I can only see a small view of that from the ticket.

**Comment by netsandbox** [comment]
@timothycrosley thanks for you quick response

Actually the source file is in a directory called `ansible`.

Here the output from the command:
```shell
>>> isort.place.module_with_reason("from ansible.inventory.manager")
('THIRDPARTY', 'Default option in Config or universal default.')
```
So a fix for me would be to tell isort `ansible` is a thirdparty module:
```shell
isort --diff --thirdparty ansible --verbose scripts/hostgroups.py

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.8.0

from-type place_module for __future__ returned FUTURE
else-type place_module for argparse returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for ansible.inventory.manager returned THIRDPARTY
from-type place_module for ansible.parsing.dataloader returned THIRDPARTY
```

But I'm not sure if all isort users are happy with this, that they always have to add this configuration if a directory name they use for their script is also the name of a python module they use.

**Comment by timothycrosley** [comment]
@netsandbox I realize my diagnostic line was a bit wrong! It should be: `isort.place.module_with_reason("ansible.inventory.manager", config=isort.Config())`

> But I'm not sure if all isort users are happy with this, that they always have to add this configuration if a directory name they use for their script is also the name of a python module they use.

Unfortunately, it's not that simple. isort is doing it's best to guess where your code begins and ends, since you haven't specified it fully using src_paths. if ansible looks like a non python source dir, it won't be included, but again this is the case where without having your full source tree it's hard to diagnose fully **why** isort thinks ansible is first party. Does it have an __init__.py in it? Does it contain a bunch of Python source files? Before isort was able to know more, because it peeked in your virtual env etc, however, this was very prone to differences when ran in CI vs local, which is much worse for most uses of isort than having to be slightly more explicit.

**Comment by netsandbox** [comment]
@timothycrosley sadly I can't share the source tree, because it contain confidential files, but I will try to setup a minimal test case.

Here the output of the updated command:

```shell
>>> isort.place.module_with_reason("ansible.inventory.manager", config=isort.Config())
('FIRSTPARTY', 'Found in one of the configured src_paths: /<redacted>/ansible.')
```
As I don't have a isort config file, isort is adding my current working directory to `src_paths`.
Maybe you can give me a hint why this is done. Because my working directory just contains yaml files and in some sub directories Python scripts, because it is used for [Ansible](https://github.com/ansible/ansible).
My working directory isn't a Python module, and I just use isort to enforce coding standards for the Python scripts inside my working directory.

**Comment by hexagonrecursion** [comment]
isort --verbose should probably be more verbose

**Comment by netsandbox** [comment]
@timothycrosley I have created a repo with a minimal test case: https://github.com/netsandbox/ansible
The problem is that I use a `ansible.inventory` module and also have a `ansible/inventory` directory, which are not related to each other.

At some point in `_src_path()`
https://github.com/PyCQA/isort/blob/f074239e5e39c2dd9e4d373e3c6ce528dae3f78c/isort/place.py#L63-L95
`ansible/inventory` ends up as `module_path` and `_is_package(module_path)`
https://github.com/PyCQA/isort/blob/f074239e5e39c2dd9e4d373e3c6ce528dae3f78c/isort/place.py#L109-L110
returns `True`.

**Comment by timothycrosley** [comment]
I don't know if your actual case is more involved than that example, but from that example It looks to me like isort is doing the right thing. Here is the easy way to prove it:

cd one level up (without being in a virtualenv), and run the following from a Python shell:

```>>> import ansible.inventory
>>> ansible.inventory.__path__
_NamespacePath(['/home/tim/Projects/isort/ansible/inventory'])
```

Python itself recognizes it as a local to namespace package. This is simply the fact that isort can't know for sure what the intent is without some additional info, and for this exact project structure that causes issues because there is some ambiguity both for people looking at the repo and isort. However, while it could know in theory like it used to via the venv, that causes havoc when combined with editors or CI, as it's subject to the the smallest change in that venv across environments - which is the norm. In general, I think it's better for isort to require a bit more explicit definition on the project side, to ensure the behavior is always the same.

For this specific example adding a `.isort.cfg` at the root of the repo with the following would suffice:

```
[settings]
known_third_party=ansible
```

or running isort via `isort --thirdparty ansible`

**Comment by netsandbox** [comment]
I understand that this a special case, but as this (the inventory directory) is also described in the [Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#using-multiple-inventory-sources), maybe some more people beside me are affected by this.

As Python themself says that a directory needs to have a `__init__.py` file to be treated as a package (see [here](https://docs.python.org/3/tutorial/modules.html#packages)), I think the `_is_package` method in
https://github.com/PyCQA/isort/blob/f074239e5e39c2dd9e4d373e3c6ce528dae3f78c/isort/place.py#L109-L110
should be extended to check also for a `__init__.py` file, like the `_is_module` method in the same file.

**Comment by timothycrosley** [comment]
That Python documentation is a bit incomplete / misleading, it's needed for a full package, but as far back as Python 3.3 no __init__.py is required in the directory for it to be a package: https://www.python.org/dev/peps/pep-0420/. A package with __init__ would take precedence, but since isort isn't looking at the venv there is know way for it to know one exists.

Is there something about ansible or otherwise that keeps adding a config, or passing --third-party ansible, from being a practical solution?

**Comment by timothycrosley** [comment]
Closing and marking this as idea for next major release, as I simply can't think of a good resolution within the limitations imposed by isort's release guarantees: https://pycqa.github.io/isort/docs/major_releases/release_policy/ that doesn't require a configuration option to be set within the project using isort. Any change here would likely also drastically change other packages import identification. I'm sorry I don't have a better resolution for the issue in the immediate turn - but I'm open to further ideas about how to resolve this and will reopen before the next release if I hear or think of a compelling one.
