### ISSUE TITLE
`language_version` override required for hook

### ISSUE THREAD

**Issue by ehontoria** [PyCQA/isort#1701]
# Describe the bug

When attempting to install the hook I would assume all you have to do is have a `.pre-commit-config.yaml` with the following configuration (for example):

```
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
        -   id: isort
            args: ["--profile", "black", "--filter-files"]
```

However, for any Python 2 environment (I am on 2.7.16) it seems you have to put in a `language_version` override to get it to install properly resulting in (something like):

```
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
        -   id: isort
            args: ["--profile", "black", "--filter-files"]
            language_version: 3.7.7
```

I believe there should be a default language version set so that you don't have to override this value.

The reason I ask about this is because other hooks like `black` for example also only run on Python 3, and it does not need this override.

# To Reproduce

1. Create a python virtual environment where the version of python is not supported for this hook
1. Attempt to create a pre-commit config without language_version set.
1. pre-commit install --install-hooks

# Expected behavior

Expected behavior is that it installs properly.

# Environment

Python Version [e.g. 3.7.1]: 2.7.16
Package version: 5.6.4
Operating System: MacOS

# Additional context

`mdformat` has the same bug, they are considering putting in `python3` as the default language version for theirs.

**Comment by timothycrosley** [comment]
Hi @ehontoria! 

You are correct that earlier versions of isorts pre-commit config were missing this, however, it has been set in isort's hooks since decemeber: https://github.com/PyCQA/isort/commit/8624101427f08b1ea6a5368040fa62b921ee224b#diff-cb921d5df435fe404b4daf451cf783709ccebe9c346038af6036644e7386c13d

I think the problem here is just that isort's documentation still links to an older version of the hook, I've updated the references to point to the latest version (5.8.0)

Thanks!

~Timothy
