### ISSUE TITLE
The order of aliased imports

### ISSUE THREAD

**Issue by elgin9507** [PyCQA/isort#1708]
Isort converts multiline imports from the same location into one line as below:

```
# INPUT
from datetime import datetime
from datetime import timedelta

# OUTPUT
from datetime import datetime, timedelta
```

But when one of the imports is aliased isort keep them on multiple lines. Example:

```
from datetime import datetime as dt
from datetime import timedelta

```

Running isort for this content doesn't result in any change. Is this a bug or expected behavior?

**Note:**  My isort conf (toml file) is as below:
```
[tool.isort]
profile = "black"
multi_line_output = 3

```

**Comment by timothycrosley** [comment]
:wave: Hi @elgin9507!

See: https://pycqa.github.io/isort/docs/configuration/options/#combine-as-imports for how to change this behavior to what you want.

---------------------------------

The reason isort defaults to the behavior it does historically, is because alias imports are seen as special enough cases that they should be called out each on a separate line - so they stand out. The reason they are seen as special is because you are dynamically renaming attributes at import time, making it harder to tell from the attribute name itself as used in code where it came from. As all choices isort makes by default, this isn't saying it's the right choice, but the project has to pick a default, and we then don't change it to avoid thrashing the code base of users that use the tool.
