### ISSUE TITLE
Not honoring src_paths the same as --src-path argument

### ISSUE THREAD

**Issue by jakebrinkmann** [PyCQA/isort#1711]
```bash
# Latest version installed via pip
$ ./.venv/bin/isort --version

                    VERSION 5.8.0

# Project Layout
$ tree .
.
└── api
    ├── myfile.py
    └── mymodule.py

# Example file with third-party and first-party imports
$ cat api/myfile.py
import sqlalchemy
import mymodule

# Example of config, including src_paths
$ cat ~/.isort.cfg
[settings]
src_paths=
    api

# Running isort
$ ./.venv/bin/isort api --sp ~/.isort.cfg
Fixing /tmp/isort-example/api/myfile.py

# Gives IMO incorrect results
$ cat api/myfile.py
import mymodule
import sqlalchemy

# Running isort again, with CLI argument
$ ./.venv/bin/isort api --src api
Fixing /tmp/isort-example/api/myfile.py

# Gives IMO correct results
$ cat api/myfile.py
import sqlalchemy

import mymodule
```

Why does `isort` need me to specify `--src-path` instead of using it from the `.isort.cfg` file?

**Comment by timothycrosley** [comment]
Hi @jakebrinkmann, 

I wrote an additional test case here: https://github.com/PyCQA/isort/commit/90ab857147966ead2e8d5832abe6e68d4934d997 confirming the config follows the expected behavior and honors the src paths setting as expected. 

I think I see the issue, 

` cat ~/.isort.cfg`

Why is a config that references a project specific src directory structure in your home folder instead of at the root of the project? Just like how when you pass it a src_path in from the command line it is relative to the location of where you ran that command, in a config file it is relative to where the config file lives. So if you set it in a config file in your home directory, it will only look for that api folder there. This is intentional, as most projects put the config at the root of their project, and if it was relative to where the command was run, would cause inconsistent results when sorting a file nested deep within the project. Is there any reason you can't place the config at the root?

**Comment by timothycrosley** [comment]
Hi @jakebrinkmann,

> I am having trouble with third-party vs first-party code when I'm using a local virtual environment:

I'm sorry to hear that! This is a common area of confusion and the docs should probably be updated to clarify how this works.

This behavior changed considerably in isort 5.0+ as detailed here: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#module-placement-changes-known_third_party-known_first_party-default_section-etc

The important thing right off the bat, is that isort already skips .venv and any modules within, and assumes **everything** is third party if it is not within the Python stdlib. You're job when using isort is just to tell it what code is yours. You can do this in multiple ways:

1. Have a typical source tree setup in a common repository layout (such as git). In this case packages would need to either be under a `src` directory or directly at the root of the repository.
2. Create a `.isort.cfg` file at the root of your project, right above all packages or top level modules. In this case packages would all need to be declared at the same level or 
3. Create a `.isort.cfg` file any were above all packages, and then directly list the src_paths relative to the location of the config file.

In your case, from what I can surmise, it looks like you have an api folder that contains Python modules, and you want all those python modules to be seen as top level modules outside of a package (instead of being `api.` namespaced). That is outside of the typical package style layout and so option #1 wouldn't work for you. You could use option #2, but that only works if api is the only directory containing Python code you want to sort, or you sort all directories separately. I think the best option is #3, in which case you would create a .isort.cfg right above the api directory that looks exactly like your example:

```
[settings]
src_paths=api,.
```

Does that solution work for you?

**Comment by jakebrinkmann** [comment]
I think I am understanding your logic, which makes a lot of sense... 

Yes, adding a `.isort.cfg` file to each of my repos would do exactly what I (said) am looking for. 

I should have mentioned I am really running `isort` in VIM (using ALE), to format a single file at a time, which makes `isort` not able to find the `.isort.cfg` in directories above

And, since I'm not quite ready to add that file to all my projects and run isort across the whole project, I will just add the following to my `~/.isort.cfg` for now and see if I can either change my workflow or think of something less against-the-grain. 

```
default_section=FIRSTPARTY
known_thirdparty=
    sqlalchemy
    marshmallow
    pytest
    requests
    ...
```

**Comment by timothycrosley** [comment]
Thanks for the additional info!

```
default_section=FIRSTPARTY
known_thirdparty=
    sqlalchemy
    marshmallow
    pytest
    requests
    ...
```
Nothing wrong with that approach! Here are two additional options that may work for your particular setup:

1. Turn back on the old finder logic (old_finders=True inside your config) - this is pretty safe as any project that do have a config added at any point will prefer the config version over what's in your home directory - but the old "magic" approach might work better for your particular setup.
2. Create a wrapping bash script for isort that sets the settings the way you want from the CLI so they will be relative to the command execution location instead of relative to the file location being sorted.
