### ISSUE TITLE
Isort not running outside script path

### ISSUE THREAD

**Issue by patrickelectric** [PyCQA/isort#1718]
version: 5.8.0
![image](https://user-images.githubusercontent.com/1215497/116747156-dfa10f00-a9d3-11eb-86d3-9d53bb84fb82.png)

**Comment by patrickelectric** [comment]
Verbose says nothing..
![image](https://user-images.githubusercontent.com/1215497/116747547-753c9e80-a9d4-11eb-8e42-4d08f4085a32.png)

**Comment by timothycrosley** [comment]
Hi @patrickelectric, it looks like (from the outside) you are experiencing the same case as: https://github.com/PyCQA/isort/issues/1497 - isort uses current working directory as the src directory if you don't explicitly provide one - simply because it has nothing else to go off of! You should be able to fix this by creating a `.isort.cfg` at the root of your project and list out the project's source directories: https://pycqa.github.io/isort/docs/configuration/config_files/

Hope this helps!

~Timothy

**Comment by patrickelectric** [comment]
Hi @timothycrosley, thanks!
We have multiple python projects under the same repository, is it possible somehow to make it run in all of them without adding each folder individually ?

With `--show-files` it displays all files under the folder, including this one, but it does not run as you can expect. 
It sounds as a bug, because running `isort $(git ls-files '*. py')`, works for some files but not for others, what is the logic ?
How can I accomplish a global isort configuration without being to maintain each repository + isort configuration.

**Comment by timothycrosley** [comment]
> With --show-files it displays all files under the folder, including this one, but it does not run as you can expect.
I don't think that's correct, I think it's running it, it's just that the only src path is the run path of isort, so the output would be different. This is common among many CLI tools, as it's unavoidable without more information provided.

> running isort $(git ls-files '*. py'), works for some files but not for others in the same root folder, what is the logic ?
Again, if I'm understanding correctly, it works for all files, it's just that in some of the cases you expect different grouping behavior that's based on the src files location being included as a sort path - which only happens if you cd into that directory when no config is setup up.

>  How can I accomplish a global isort configuration without being to maintain each repository + isort configuration.

One option would be to create and then reuse your own custom shared profile - see https://github.com/PyCQA/isort/tree/main

However, if the stated case is correct:

> We have multiple python projects under the same repository, is it possible somehow to make it run in all of them without adding each folder individually ?

Just put your config as a .isort.cfg in the root of your repository and list out any sort paths.

**Comment by patrickelectric** [comment]
> it's just that the only src path is the run path of isort, so the output would be different. This is common among many CLI tools.

This tools also provide a way to change the running directory, is there such option with isort ? like: `--git-dir for git`.



> Just put your config as a .isort.cfg in the root of your repository and list out any source paths.

Is there a way to accomplish it via command line ?

**Comment by patrickelectric** [comment]
In the end I got `dirname $(git ls-files "*/setup.py") | xargs -I {} isort --src-path={} {}` to do the trick, I'm not sure if there is a better way to accomplish such thing.

**Comment by timothycrosley** [comment]
> is there such option with isort ? like: --git-dir for git.

The only option isort uses the current directory for is to populate the default source paths. So the direct equivalent of `--git-dir` is indeed `--src-path`
