### ISSUE TITLE
isort --atomic fails on Cython "cimport" syntax

### ISSUE THREAD

**Issue by DanielFEvans** [PyCQA/isort#1722]
`isort --atomic` fails for any Cython .pyx file containing a `cimport` statement, claiming it has an existing syntax error. A minimal example is:

```
cimport numpy
cimport ctime
```

`isort buggy.pyx --diff` runs fine:
```
$ isort buggy.pyx --diff
--- .../buggy.pyx:before       2021-05-06 10:19:09.495635
+++ .../buggy.pyx:after        2021-05-06 10:19:19.479452
@@ -1,2 +1,2 @@
+cimport ctime
 cimport numpy
-cimport ctime
Fixing .../buggy.pyx
```

However, `isort buggy.pyx --diff --atomic` fails:
```
$ isort buggy.pyx --diff --atomic
.../lib/python3.6/site-packages/isort/api.py:306: UserWarning: {file_path} unable to sort due to existing syntax errors
```

Bug found on isort v5.8.0, but the bug exists as far back as isort v5.0.0, when Cython support was added.

I presume the same issue will occur for any other Cython-specific syntax, too.

**Comment by timothycrosley** [comment]
Hi @DanielFEvans,

Sorry you experienced this error! I could see how it could be jarring! It is correct that atomic is incomptible with Cython, but that is simply because atomic is based fully on the ability to parse it after sorting with the CPython AST. I think  expanding support to Cython as well would be awesome!

**Comment by DanielFEvans** [comment]
Is it possible to enable atomic for normal Python and simultaneously disable it for Cython files? I've not spotted any configurability like that, but there are a lot of options!

**Comment by timothycrosley** [comment]
It seems unlikely that Cython will in short order expose an AST parsing API so in the meantime, Ive improved the behavior to warn in verbose mode instead of fail when a Cython exentioned file contains a Python AST error. Hopefully, at some point in the future, Cython files will also be able to fully be checked for ast errors.

**Comment by JohnHBrock** [comment]
With v5.9.1, I still see this error if I use the `--check-only` flag, e.g.:
```sh
$ isort --atomic --check-only buggy.pyx
ERROR: isort was told to sort imports within code that contains syntax errors: .../buggy.pyx.
```
Is this intentional?

**Comment by timothycrosley** [comment]
@JohnHBrock no it is not intentional! I have pushed an change to fix this to the main branch, and plan to push a new release to PyPI sometime over the next week.
