### ISSUE TITLE
isort inserts blank line before noqa imports

### ISSUE THREAD

**Issue by jwodder** [PyCQA/isort#1765]
isort version: 5.9.1
Python version: 3.9.5

Python code:

```python
import re
import readline  # noqa
```

`.isort.cfg`:
```ini
[settings]
atomic = True
force_sort_within_sections = True
honor_noqa = True
lines_between_sections = 0
profile = black
reverse_relative = True
sort_relative_in_force_sorted_sections = True
src_paths = src
```

Running isort on the above file with the given settings produces the following:

```python
import re

import readline  # noqa
```

For some reason, a blank line has been inserted before the `readline` import.  This does not happen if I remove the `# noqa` comment or if I use a different comment.  I cannot find any configuration option in the documentation that would cause or prevent this.  I would like to request that isort not insert a blank line before `noqa`-commented imports, or at least provide an option to control this behavior.

**Comment by anirudnits** [comment]
Hey @jwodder, this is actually the expected behavior, what is happening is that `isort` processes all the imports without `noqa` and sorts them and then places the `noqa` imports after all the sorted imports. To workaround the extra blank line, you can make the `lines_after_imports` as 0 and that should remove the extra blank line before the `noqa` import, https://github.com/PyCQA/isort/blob/main/docs/configuration/options.md#lines-between-sections. I tried it out locally and it seems to work for the imports and the options you referenced.

Hope this helps.

**Comment by jwodder** [comment]
@anirudnits Setting `lines_after_imports` to 0 gets rid of *every* blank line after imports in every file; e.g., this:

```python
import re

def func(x):
    ...
```

becomes this:

```python
import re
def func(x):
    ...
```

That's much, much worse than a blank line before noqa imports.

**Comment by timothycrosley** [comment]
This is intentional, there is no perfect option to take here but IMHO isort is taking the best of the imperfect options. When you tell isort to skip a line, you're telling it to treat it as any other non handled by isort line. The honor_noqa option, is essentially a "treat all noqa comments" comments as isort: skip comments, and it is behaving as told. Since the processing of that import line is skipped it can't even tell what it is or if it's a group, trying to be clever here would be not skipping, which is what the comment is asking for isort to do. A simple example that illustrates this, is if isort starts going down this line of thinking, there's going to be an expectation that this is handled

```
import os
import request # isort: skip
import fastapi
```
by inserting the blank line between os and requests, but that also this is handled:

```
import os
import os.path # isort: skip
import fastapi
```

by inserting the blank line between fast api and os.path. Clearly this kind of logic requires not skipping. So skipped lines must be treated as all other code and left in there own section. Generally a better question to ask is why you need the skip at all?
