### ISSUE TITLE
isort adds spurious type ignore

### ISSUE THREAD

**Issue by hauntsaninja** [PyCQA/isort#1768]
Given the following file:
```
from a import (
    bbbbbbbbbb,
    cccccccccc,
    dddddddddd,
    eeeeeeeeee,
    ffffffffff,
    gggggggggg,
    hhhhhhhhhh,
    iiiiiiiiii,
    jjjjjjjjjj,
    kkkkkkkkkk,
    llllllllll,
    mmmmmmmmmm,
    nnnnnnnnnn,
)
from a import o as o
from a import (  # type: ignore
    pppppppppp,
    qqqqqqqqqq,
    rrrrrrrrrr,
    ssssssssss,
    tttttttttt,
    uuuuuuuuuu,
    vvvvvvvvvv,
    wwwwwwwwww,
    xxxxxxxxxx,
    yyyyyyyyyy,
    zzzzzzzzzz,
)
```

isort will add a spurious `type: ignore` to the first line:
```
λ isort x.py --diff
--- <pwd>/x.py:before	2021-06-29 18:13:17.428484
+++ <pwd>/x.py:after	2021-06-29 18:13:24.847848
@@ -1,4 +1,4 @@
-from a import (
+from a import (  # type: ignore
     bbbbbbbbbb,
     cccccccccc,
     dddddddddd,
```

**Comment by timothycrosley** [comment]
Hi @hauntsaninja,

I can see why this would be confusing!  It is however, intentional, and there is little that can be done about it while still enabling isort to sort imports. Essentially, you're intending to comment a line, but isort cant think about imports as individual lines and still move them around. You have 2 separate groups of from imports from the a package, and isort has to attach the comments to all a package references in order to move imports without removing comments (which would be much worse!)

See the following example:
```
from a import (
    cccccccccc,
    dddddddddd,
    eeeeeeeeee,
    ffffffffff,
    gggggggggg,
    hhhhhhhhhh,
    iiiiiiiiii,
    jjjjjjjjjj,
    kkkkkkkkkk,
    llllllllll,
    mmmmmmmmmm,
    nnnnnnnnnn,
)
from a import o as o
from a import (  # type: ignore
    bbbbbbbbbb,   # <--- what I actually need the type: ignore comment for
    pppppppppp,
    qqqqqqqqqq,
    rrrrrrrrrr,
    ssssssssss,
    tttttttttt,
    uuuuuuuuuu,
    vvvvvvvvvv,
    wwwwwwwwww,
    xxxxxxxxxx,
    yyyyyyyyyy,
    zzzzzzzzzz,
)
```

Under this approach the bbbbbbbbbb would need to move to the top, but then would lose the type ignore comment.
How your example is written the only thing to attach the comment to is the package and so isort is doing the best thing.

If you don't want it to be attached to the package, just directly comment the individual imports that need to have the comment, and isort will be able to keep this intention, and only list the comment once:

```
from a import (
    cccccccccc,
    dddddddddd,
    eeeeeeeeee,
    ffffffffff,
    gggggggggg,
    hhhhhhhhhh,
    iiiiiiiiii,
    jjjjjjjjjj,
    kkkkkkkkkk,
    llllllllll,
    mmmmmmmmmm,
    nnnnnnnnnn,
)
from a import o as o
from a import (
    bbbbbbbbbb,  # type: ignore
    pppppppppp,
    qqqqqqqqqq,
    rrrrrrrrrr,
    ssssssssss,
    tttttttttt,
    uuuuuuuuuu,
    vvvvvvvvvv,
    wwwwwwwwww,
    xxxxxxxxxx,
    yyyyyyyyyy,
    zzzzzzzzzz,
)
```

And, if your need very bespoke and comment placement, you can always turn isort: off and back on with action comments, and ideally some additional comments to explain why the weirdness is needed.

Hope this is helpful!

~Timothy
