### ISSUE TITLE
Feature request: separate TYPE_CHECKING

### ISSUE THREAD

**Issue by juanolon** [PyCQA/isort#1795]
Hello,
I was looking for a option to separate my imports, which are only for type checking from all the others, and wrap them into an if block. I look into the issues and only found this thread: https://github.com/PyCQA/isort/issues/818#issuecomment-466644848

It would convert this:
```
from torch.utils.data.dataset import Dataset
from argparse import ArgumentParser
import torch
```
to
```
if TYPE_CHECKING:
    from torch.utils.data.dataset import Dataset

from argparse import ArgumentParser
import torch
```

That would be huge. Thanks!

**Comment by timothycrosley** [comment]
Hi @juanolon,

I can see why this would be useful, but unfortunately, while it may seem simple on the outside, it goes well behind what isort could reasonably support. isort only looks at, parses, and understands imports. This would require it to fully understand all syntax elements to even get it right most of the time. Even if it did that, it would still fail plenty of times, where either the import has a side effect that's intentional, or the annotation is meant for runtime (ala fastapi).

Sorry!

~Timothy

**Comment by juanolon** [comment]
ic. thanks anyway!

**Comment by NeilGirdhar** [comment]
@timothycrosley Any chance you could revisit this now that a flake8 [plugin](https://github.com/snok/flake8-type-checking) suggests putting things under type checking blocks?  We would only need to support `if TYPE_CHECKING`, and no other constructs.
