### ISSUE TITLE
Pytest importorskip not recognized in combination with float_to_top option

### ISSUE THREAD

**Issue by fjetter** [PyCQA/isort#1798]
The default isort configuration respects ordering of `pytest.importorskip` calls and sorts them properly in a way it makes sense, see also https://github.com/PyCQA/isort/issues/786 for the initial report.

When using `float_to_top` this behaviour is no longer respected and all imports are moved above the importorskip.

(Copying example of the other issue for clarification)

```python
import pytest
import numpy as np

asdf = pytest.importorskip('asdf')

import asdf.utils

```

becomes after `isort --float-to-top`

```python
import asdf.utils
import numpy as np
import pytest

asdf = pytest.importorskip('asdf')
```

**Comment by timothycrosley** [comment]
Unfortunately, these two goals are at odds and isort can't reasonable support what is asked here. You either have import groups sorted where they are, or you force imports all to the top of the file. isort can't support both, because then every special case would submit a ticket and the code base would become very complicated, and float_to_top would overtime become the same as not float_to_top.

**Comment by timothycrosley** [comment]
My own recommendation here, would be to run float to top, occasionally, if desired, as a house cleaning mechanism, manually fixing any desired edge cases. But keeping it off as a project wide configuration.

**Comment by fjetter** [comment]
Thanks, I already figured this is not a supported you case but wanted to check in case this was a buggy
