### ISSUE TITLE
Imports on same line

### ISSUE THREAD

**Issue by alexreg** [PyCQA/isort#1830]
Right now, if I have, e.g.,

```python
from a import foo
from a import bar
```

and isort reformats this to

```python
from a import foo, bar
```

I am fine with this as long as `foo` and `bar` are functions (or anything but modules). But if they are modules, I want them to remain on separate lines. Unfortunately, the `--force-single-line-imports` option is an "all or nothing" option. Could there perhaps be an option to just do nothing with respect to imports being split across multiple lines or not? Alternatively, a smart option to recognise modules vs. non-modules, but I imagine this would be significantly harder and not worth the effort.

**Comment by alexreg** [comment]
@anirudnits Thanks for the quick response. And yes, that's exactly right.

**Comment by timothycrosley** [comment]
This goes beyond what I think is reasonable for the project to take on. I think it is simply too niche to be maintainable, as I've never seen, heard, or otherwise seen whisperings of a similar pattern when organizing imports. If this ends up being a common pattern, certainly I'm open to revisiting it.

**Comment by nuh-temp** [comment]
If having 
```
from a import b, c
```
may be okay, but having 
```
from a import a, b as lib_b, c, d as lib_d
```
makes it completely unreadable, also I'd prefer if `isort` skips on packing multiple import into a single line and just sort them.
