### ISSUE TITLE
`isort` does not search for config when using `--filename`

### ISSUE THREAD

**Issue by karthiknadig** [PyCQA/isort#1989]
If you have files in this structure:
```
project
   |- sub-package
        |- pyproject.toml
        |- something.py       
```
say that `pyproject.toml` configures for profile black.

Then, this works (picks up the profile black):
```
C:\project> python -m isort C:\project\sub-package\something.py
```
but this does not:
```
C:\project> type C:\project\sub-package\something.py | python -m isort - --filename C:\project\sub-package\something.py
```
but this does (notice the CWD)
```
C:\project\sub-package> type C:\project\sub-package\something.py | python -m isort - --filename C:\project\sub-package\something.py
```

In VS Code extension for `isort` we are using the stdin way to perform sorting. This is need to support the organize import on save capability. I was able to simulate the same problem using `type` (on windows) and `cat` (on linux). 

reference issue: https://github.com/microsoft/vscode-isort/issues/138

**Comment by karthiknadig** [comment]
Related: https://github.com/PyCQA/isort/issues/1940

**Comment by kaste** [comment]
This looks like introduced via https://github.com/PyCQA/isort/commit/09734212dd6c661c563a062ee91c9302deacada4
which looks like a very strange commit because it just removes a line and it is not obvious why this should be okay.  The line was introduced like a hotfix here: https://github.com/PyCQA/isort/commit/c0ebbd0ff097abafd1f0060a5021b553efebc192

So generally the workaround is to just use `--settings_path` but with a path not the absolute file name.  (`--filename` is a config option just used for the stdin case and basically does a `settings_path = dirname(filename)`.  I do a possible PR here but wasted now an hateful hour or so to get poetry to install this package, let alone run the tests.  Damn.  

```
Because isort depends on pip (>=21.1.1) which doesn't match any versions, version solving failed.
```
