### ISSUE TITLE
Incorrect sorting when module is named `test`.

### ISSUE THREAD

**Issue by WloHu** [PyCQA/isort#2085]
When I run `isort` in my project for a file with content below then imports are improperly sorted.
```python
import os
from functools import partial

import pytest

from domain.more.modules import stuff
from test.domain.conftest import test_stuff
```
Result:
```python
import os
from functools import partial
from test.domain.conftest import test_stuff

import pytest

from domain.more.modules import stuff
```

Expected: no change.

However when I renamed `test` to `tests` in the file then it works as expected. So for:
```python
import os
from functools import partial

import pytest

from domain.more.modules import stuff
from tests.domain.conftest import test_stuff
```
Nothing is changed when `isort` is run.

**Comment by timothycrosley** [comment]
isort is sorting it this way because `test` is part of stdlib: https://docs.python.org/3/library/test.html and therefore really shouldn't be used as a project namespace. You can still make this work if you need to do this for an existing project that overrides the stdlib module, by setting this: https://pycqa.github.io/isort/docs/configuration/options.html#known-first-party
